name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lijinch-aspnet:latest;
           docker login -u raymondlee915 -p ${{PKGTOKEN}} docker.pkg.github.com;
           docker tag lijinch-aspnet:latest docker.pkg.github.com/raymondlee915/aspnet/lijinch-aspnet:latest;
           docker push docker.pkg.github.com/raymondlee915/aspnet/lijinch-aspnet:latest
